### ISSUE TITLE
Simulation stalls when initialising WFS objects in Debian

### ISSUE THREAD

**Issue by nab-durham** [andrewpaulreeves/soapy#15]
OS: Debian Wheezy
Software configuration: from repository plus compiled-from-source numpy 1.9.2 and ipython-qtconsole from backports (sid) -- the latter only to operate the GUI.

Trying to run any supplied python code (testSimulation.py, testWfs.py) with or without the GUI stalls after the line 'Initialising WFS' or after print two full stops.

**Comment by andrewpaulreeves** [comment]
This seems odd as its not shown up in any other situation. The only part of WFS initialisation which features any compiled code which could cause this kind of thing would be the FFT initialisation. I'll have a look...

**Comment by andrewpaulreeves** [comment]
The same error has been noticed using ubuntu 12.04, and was diagnosed to be an issue with SciPy interp2d. Fixed by updating scipy to newer version.

Can you test @nab-durham?
