### ISSUE TITLE
DM actuators

### ISSUE THREAD

**Issue by andrewpaulreeves** [andrewpaulreeves/soapy#21]
For vaguely historical reasons, the number of DM actuators for stackarray DMs is expressed as ``nx**2``, whereas the number of wfs subaps for SH WFSs is expressed as ``nx``. Perhaps these should be made consistent?

**Comment by matthewtownson** [comment]
maybe should be total number of subaps/actuators?

If it is a square number then arrange like it is currently, but might allow in the future users to have different layouts of actuators in a DM by specifying the locations of the actuators somewhere maybe?

**Comment by andrewpaulreeves** [comment]
This has now been implemented, nxActuators should be set to be the 1d number of acts for stackarray DMs
