### ISSUE TITLE
Add latency to the control loop

### ISSUE THREAD

**Issue by jwoillez** [andrewpaulreeves/soapy#32]
@andrewpaulreeves - Would you consider a PR adding a latency parameter to the loop?

Skimming through the code, I would add a fifo of configurable size to `Sim.loopFrame()`, between the calls to `reconstruct()` and `runDM()`. The parameter would be the latency as an integer multiple of `loopTime`.

PS: Thank so much! Finally a python tool for AO simulations. \o/

**Comment by andrewpaulreeves** [comment]
Hi @jwoillez!

That would be great! That certainly sound like the correct way to implement it, would you be willing to give it a go and submit a pull request?

**Comment by jwoillez** [comment]
Certainly! Stay tune...
